services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\DataFixtures\BookieTestFixtureInterface:
            tags: ['doctrine.fixture.orm']

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
