version: "2"
services:
    source:
        build: ./docker/source
        container_name: bookie_php_vue
        working_dir: /var/www/bookie-front
        env_file:
            - ./docker/source/vars.env
        volumes:
            - ./backend:/var/www/bookie-api:delegated
            - ./frontend:/var/www/bookie-front:delegated
        expose:
            - 9000
        restart: always

    web:
        build: ./docker/web
        container_name: bookie_nginx
        working_dir: /etc/nginx
        depends_on:
            - source
        ports:
            - 80:80
        volumes_from:
            - source
        restart: always

    database:
        image: mysql:5.7
        container_name: bookie_mysql
        depends_on:
            - source
        ports:
            - 3306:3306
        env_file:
            - ./docker/database/vars.env
        volumes:
            - ./var/mysql:/var/lib/mysql:cached
        restart: always
