version: "2"
services:
    backend:
        build: docker/php
        container_name: wallace_php
        working_dir: /var/www/bookie-api
        env_file:
            - docker/php/vars.env
        volumes:
            - ./backend:/var/www/bookie-api:delegated
        expose:
            - 9000
        restart: always

    web_server:
        build: docker/nginx
        container_name: wallace_nginx
        working_dir: /etc/nginx
        depends_on:
            - backend
        ports:
            - 80:80
        volumes_from:
            - backend
        restart: always

    database:
        image: mysql:5.7
        container_name: wallace_mysql
        depends_on:
            - backend
        ports:
            - 3306:3306
        env_file:
            - docker/mysql/vars.env
        volumes:
            - ./var/mysql:/var/lib/mysql:cached
        restart: always

#    frontend:
#        image: node:9.11-stretch
#        container_name: wallace_node
#        restart: always
