# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener: true
    exception:
        enabled: true
        codes:
            App\Exception\DuplicateRessourceException: HTTP_BAD_REQUEST
            App\Exception\BetFormatException: HTTP_BAD_REQUEST
            App\Exception\MatchStartedException: HTTP_BAD_REQUEST
            App\Exception\ScoreFormatException: HTTP_BAD_REQUEST
            Symfony\Component\Validator\Exception\ValidatorException: HTTP_BAD_REQUEST
            Doctrine\ORM\EntityNotFoundException: HTTP_NOT_FOUND
#            Symfony\Component\Security\Core\Exception\AccessDeniedException: HTTP_FORBIDDEN
#            \Exception: HTTP_INTERNAL_SERVER_ERROR
        messages:
            App\Exception\DuplicateRessourceException: true
            App\Exception\BetFormatException: true
            App\Exception\MatchStartedException: true
            App\Exception\ScoreFormatException: true
            Symfony\Component\Validator\Exception\ValidatorException: true
            Doctrine\ORM\EntityNotFoundException: true
#            Symfony\Component\Security\Core\Exception\AccessDeniedException: true
            \Exception: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
    body_converter:
        enabled: true
        validate: true
